/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommunicationChannel = IDL.Variant({
  'whatsapp' : IDL.Null,
  'email' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientType = IDL.Variant({
  'gst' : IDL.Null,
  'itr' : IDL.Null,
  'both' : IDL.Null,
});
export const InvoiceLineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'clientType' : ClientType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'clientId' : IDL.Nat,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'gstPercentage' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClientReply = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
  'channel' : CommunicationChannel,
});
export const SenderConfig = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClientReply' : IDL.Func(
      [IDL.Nat, CommunicationChannel, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ClientType],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Nat, IDL.Vec(InvoiceLineItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getRepliesForClient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClientReply)],
      ['query'],
    ),
  'getSenderConfig' : IDL.Func([], [IDL.Opt(SenderConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ClientType],
      [],
      [],
    ),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(InvoiceLineItem), IDL.Nat],
      [],
      [],
    ),
  'updateSenderConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommunicationChannel = IDL.Variant({
    'whatsapp' : IDL.Null,
    'email' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientType = IDL.Variant({
    'gst' : IDL.Null,
    'itr' : IDL.Null,
    'both' : IDL.Null,
  });
  const InvoiceLineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'clientType' : ClientType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'clientId' : IDL.Nat,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'gstPercentage' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClientReply = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
    'channel' : CommunicationChannel,
  });
  const SenderConfig = IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClientReply' : IDL.Func(
        [IDL.Nat, CommunicationChannel, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ClientType],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Nat, IDL.Vec(InvoiceLineItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getRepliesForClient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClientReply)],
        ['query'],
      ),
    'getSenderConfig' : IDL.Func([], [IDL.Opt(SenderConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ClientType],
        [],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(InvoiceLineItem), IDL.Nat],
        [],
        [],
      ),
    'updateSenderConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };