/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'clientType' : ClientType,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface ClientReply {
  'id' : bigint,
  'clientId' : bigint,
  'message' : string,
  'timestamp' : Time,
  'channel' : CommunicationChannel,
}
export type ClientType = { 'gst' : null } |
  { 'itr' : null } |
  { 'both' : null };
export type CommunicationChannel = { 'whatsapp' : null } |
  { 'email' : null };
export interface Invoice {
  'id' : bigint,
  'lineItems' : Array<InvoiceLineItem>,
  'clientId' : bigint,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'gstPercentage' : bigint,
}
export interface InvoiceLineItem {
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface SenderConfig { 'email' : string, 'phone' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClientReply' : ActorMethod<
    [bigint, CommunicationChannel, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<
    [string, string, string, string, string, ClientType],
    bigint
  >,
  'createInvoice' : ActorMethod<
    [bigint, Array<InvoiceLineItem>, bigint],
    bigint
  >,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getRepliesForClient' : ActorMethod<[bigint], Array<ClientReply>>,
  'getSenderConfig' : ActorMethod<[], [] | [SenderConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<
    [bigint, string, string, string, string, string, ClientType],
    undefined
  >,
  'updateInvoice' : ActorMethod<
    [bigint, bigint, Array<InvoiceLineItem>, bigint],
    undefined
  >,
  'updateSenderConfig' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];